# Generated by Django 4.2.7 on 2023-11-10 21:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('exp_date', models.DateTimeField(default=datetime.datetime(2023, 11, 17, 21, 1, 13, 679583, tzinfo=datetime.timezone.utc), verbose_name='expiration date')),
            ],
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('question_text__length__gte', 1)), name='question_text_length'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(('exp_date__gte', models.F('pub_date'))), name='Expiration date'),
        ),
    ]
