# Generated by Django 4.2.7 on 2023-11-11 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DogsAndCats_content', '0003_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('email__length__gte', 5)), name='Email must be at least 5 character'),
        ),
    ]
